# Generated by Django 4.1.7 on 2023-04-04 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('repuestos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='repuesto',
            options={'ordering': ['nombre']},
        ),
    ]
