# Generated by Django 4.1.7 on 2023-03-30 01:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('repuestos', '0001_initial'),
        ('vehiculos', '0001_initial'),
        ('proveedores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mantenimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('C', 'Correctivo'), ('P', 'Preventivo')], max_length=1)),
                ('ot', models.CharField(blank=True, max_length=20)),
                ('os', models.BooleanField(default=False)),
                ('fecha', models.DateField(auto_now_add=True)),
                ('fecha_preventivo', models.DateField(blank=True, null=True)),
                ('descripcion', models.CharField(blank=True, max_length=400)),
                ('estado', models.BooleanField(default=True)),
                ('placa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehiculos.vehiculo')),
                ('proveedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='proveedores.proveedor')),
            ],
        ),
        migrations.CreateModel(
            name='RepuestoMantenimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('descripcion', models.CharField(blank=True, max_length=200)),
                ('mantenimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mantenimientos.mantenimiento')),
                ('repuesto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='repuestos.repuesto')),
            ],
        ),
        migrations.AddField(
            model_name='mantenimiento',
            name='repuestos',
            field=models.ManyToManyField(blank=True, through='mantenimientos.RepuestoMantenimiento', to='repuestos.repuesto'),
        ),
    ]
