# Generated by Django 4.1.7 on 2023-04-04 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proveedores', '0001_initial'),
        ('mantenimientos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mantenimiento',
            name='proveedor',
        ),
        migrations.AddField(
            model_name='mantenimiento',
            name='proveedores',
            field=models.ManyToManyField(blank=True, to='proveedores.proveedor'),
        ),
    ]
