# Generated by Django 4.1.7 on 2023-04-05 10:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mantenimientos', '0002_remove_mantenimiento_proveedor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mantenimiento',
            name='fecha',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
