# Generated by Django 4.1.7 on 2023-04-06 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mantenimientos', '0004_alter_mantenimiento_fecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='repuestomantenimiento',
            name='DELETE',
            field=models.BooleanField(default=False),
        ),
    ]
