# Generated by Django 4.1.7 on 2023-04-06 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mantenimientos', '0005_repuestomantenimiento_delete'),
    ]

    operations = [
        migrations.RenameField(
            model_name='repuestomantenimiento',
            old_name='DELETE',
            new_name='eliminado',
        ),
    ]
