# Generated by Django 4.1.7 on 2023-04-20 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mantenimientos', '0007_alter_repuestomantenimiento_repuesto'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mantenimiento',
            options={'ordering': ['-fecha']},
        ),
    ]
