# Generated by Django 4.1.7 on 2023-03-30 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(max_length=7, unique=True)),
                ('tipo', models.CharField(choices=[('PT', 'PT'), ('MT', 'MT')], default='PT', max_length=2)),
                ('marca', models.CharField(default='Chevrolet', max_length=50)),
                ('modelo', models.CharField(default='N300', max_length=50)),
                ('anio', models.PositiveIntegerField(blank=True, null=True)),
                ('regional', models.CharField(default='03', max_length=2)),
            ],
        ),
    ]
