# Generated by Django 4.1.7 on 2023-04-04 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vehiculo',
            options={'ordering': ['placa']},
        ),
    ]
