# Generated by Django 4.1.7 on 2023-03-30 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('celular', models.CharField(blank=True, max_length=20)),
                ('correo', models.EmailField(blank=True, max_length=254)),
                ('tipo', models.CharField(blank=True, choices=[('M', 'Mecánico'), ('E', 'Electricista'), ('S', 'Proveedor de servicios')], max_length=1)),
                ('descripcion', models.CharField(blank=True, max_length=200)),
            ],
        ),
    ]
